Add TSC meeting minutes for 2021-02-25
oss-review-toolkit/ort-governance pull request #21
Opened 2021-06-08 10:03 UTC by mnonnenmacher

2021-06-09 06:06 UTC, sschuberth requested changes

2021-07-01 10:40 UTC, mnonnenmacher commented on minutes/2021-02-25.md
> +@mnonnenmacher, @tsteenbe, @sschuberth, @fviernau
We only had them in the minutes for 2020-10-23 so far. Done.

2021-07-01 10:41 UTC, mnonnenmacher commented on minutes/2021-02-25.md
> +LFX Insights and Security onboarding has started.
Done.

2021-07-01 11:00 UTC, sschuberth approved these changes

2021-07-01 21:22 UTC, merged